superlists/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$', 'electricity_charge.views.home_page', name='home'),
    url(r'^electricity_charge/(\d+)/$', 'electricity_charge.views.view_calculation',
        name='view_calculation'
    ),
    url(r'^electricity_charge/(\d+)/add_electronic$', 'electricity_charge.views.add_electronic',
        name='add_electronic'
    ),
    url(r'^electricity_charge/new$', 'electricity_charge.views.new_calculation', name='new_calculation'),
    # url(r'^admin/', include(admin.site.urls)),
)

electricity_charge/models.py
from django.db import models

class Calculation(models.Model):
    pass

class Electronic(models.Model):
    name = models.TextField(default='')
    number = models.IntegerField(default=0)
    power = models.IntegerField(default=0)
    time = models.FloatField(default=0)
    unit = models.FloatField(default=0)
    calculation = models.ForeignKey(Calculation, default=None)

electricity_charge/views.py
from django.shortcuts import redirect, render
from electricity_charge.models import Electronic, Calculation
from sys import maxsize

def home_page(request):
     return render(request, 'home.html',{
            'sum_unit' : '0',
            'cost_unit' : '0.0',
            'ft' : '10.04',
            'cost_add_ft' : '0.0',
            'vat' : '0.0',
            'net_cost' : '0.0',
    })

def view_calculation(request, calculation_id):
    calculation_ = Calculation.objects.get(id=calculation_id)
    electronics = Electronic.objects.filter(calculation=calculation_)
    sum_unit = 0
    for elec in electronics:
        sum_unit = sum_unit + elec.unit

    cost_unit = 0
    if sum_unit < 150:
        cost_unit = cost_less_than_150_units_a_month(sum_unit)
    else:
        cost_unit = cost_more_than_150_units_a_month(sum_unit)

    ft = 10.04
    cost_add_ft = cost_unit + (sum_unit*ft/100)

    return render(request, 'electricity_charge.html',{
        'electronics' : electronics,
        'sum_unit' : sum_unit,
        'cost_unit' : cost_unit,
        'ft' : ft,
        'cost_add_ft' : cost_add_ft,
        'vat' : 7*(cost_add_ft)/100,
        'net_cost' : 107*(cost_add_ft)/100,
        'calculation' : calculation_,
    })

def new_calculation(request):
    calculation_ = Calculation.objects.create()
    Electronic.objects.create(
        name=request.POST['name_text'],
        number=int(request.POST['number_text']),
        power=int(request.POST['power_text']),
        time=float(request.POST['time_text']),
        unit= float((int(request.POST['power_text'])/1000)*int(request.POST['number_text'])*float(request.POST['time_text'])),
        calculation=calculation_)
    return redirect('/electricity_charge/%d/' % (calculation_.id,))


def add_electronic(request, calculation_id):
    calculation_ = Calculation.objects.get(id=calculation_id)
    Electronic.objects.create(
        name=request.POST['name_text'],
        number=int(request.POST['number_text']),
        power=int(request.POST['power_text']),
        time=float(request.POST['time_text']),
        unit= float((int(request.POST['power_text'])/1000)*int(request.POST['number_text'])*float(request.POST['time_text'])),
        calculation=calculation_)
    return redirect('/electricity_charge/%d/' % (calculation_.id,))
  
def cost_less_than_150_units_a_month(unit):
    cost_per_unit = [1.3576,1.5445,1.7968,2.1800,2.2734,2.7781,2.9780]
    unit_rate = [5,10,10,10,65,250,maxsize]
    cost = 0
    rate_index = 0

    while unit > 0:
        if unit - unit_rate[rate_index] > 0:
            unit_of_this_cost = unit_rate[rate_index]
        else:
            unit_of_this_cost = unit
        cost = cost + (unit_of_this_cost*cost_per_unit[rate_index])
        unit = unit - unit_rate[rate_index]
        if rate_index < 6:
            rate_index = rate_index +1
        else:
            rate_index = 6
    return cost + 8.19 #บวกค่าบริการรายเดือน

def cost_more_than_150_units_a_month(unit):
    cost_per_unit = [1.8047,2.7781,2.9780]
    unit_rate = [150,400,maxsize]
    cost = 0
    rate_index = 0

    while unit > 0:
        if unit - unit_rate[rate_index] > 0:
            unit_of_this_cost = unit_rate[rate_index]
        else:
            unit_of_this_cost = unit
        cost = cost + (unit_of_this_cost*cost_per_unit[rate_index])
        unit = unit - unit_rate[rate_index]
        if rate_index < 2:
            rate_index = rate_index +1
        else:
            rate_index = 2
    return cost + 40.90 #บวกค่าบริการรายเดือน

electricity_charge/templates/electricity_charge.html
<html>
    <head>
        <title>Electricity Charge Calculator</title>
    </head>
    <body>
        <h1>Your Calculation Name</h1>
        <form method="POST" action="/electricity_charge/{{ calculation.id }}/add_electronic">
        <table id="electronics_data_table"><tr>
            <td><input name="name_text" id="name_box" placeholder="New Electronic's Name" /></td>
            <td><input name="number_text" id="number_box" placeholder="Number" /></td>
            <td><input name="power_text" id="power_box" placeholder="Power (watts)" /></td>
            <td><input name="time_text" id="time_box" placeholder="Time (hours a day)" /></td>
            <td><input id="submit_data" type="submit" value="Submit"></td>
        </tr>
        {% csrf_token %}

        </form>

            <tr>
	        <td>Electronics's Name</td>
	        <td>Number</td>
	        <td>Power (watts)</td>
	        <td>Time (hours/day)</td>
	        <td>Electricity Usage Unit (units)</td>
            </tr>
        {% for electronic in calculation.electronic_set.all %}
	    <tr>
	        <td>{{ electronic.name }}</td>
	        <td>{{ electronic.number }}</td>
	        <td>{{ electronic.power }}</td>
	        <td>{{ electronic.time }}</td>
	        <td>{{ electronic.unit }}</td>
            </tr>
        {% endfor %}
	    <tr>
	        <td></td>
	        <td></td>
	        <td></td>
	        <td>Sum units</td>
	        <td>{{ sum_unit }} Units</td>
            </tr>
	    <tr>
	        <td></td>
	        <td></td>
	        <td></td>
	        <td>Cost</td>
	        <td>{{ cost_unit }} THB</td>
            </tr>
	    <tr>
	        <td></td>
	        <td></td>
	        <td></td>
	        <td>ft of JAN-APR 2015</td>
	        <td>{{ ft }} Stangs/Unit</td>
            </tr>
	    <tr>
	        <td></td>
	        <td></td>
	        <td></td>
	        <td>Cost (add ft)</td>
	        <td>{{ cost_add_ft }} THB</td>
            </tr>
	    <tr>
	        <td></td>
	        <td></td>
	        <td></td>
	        <td>VAT 7%</td>
	        <td>{{ vat }} THB</td>
            </tr>
	    <tr>
	        <td></td>
	        <td></td>
	        <td></td>
	        <td>NET COST</td>
	        <td>{{ net_cost }} THB</td>
            </tr>
        </table>
    </body>
</html>

electricity_charge/templates/home.html
<html>
    <head>
        <title>Electricity Charge Calculator</title>
    </head>
    <body>
        <h1>Start a New Electricity Charge Calculation</h1>
        <form method="POST" action="/electricity_charge/new">
        <table><tr>
            <td><input name="name_text" id="name_box" placeholder="New Electronic's Name" /></td>
            <td><input name="number_text" id="number_box" placeholder="Number" /></td>
            <td><input name="power_text" id="power_box" placeholder="Power (watts)" /></td>
            <td><input name="time_text" id="time_box" placeholder="Time (hours a day)" /></td>
            <td><input id="submit_data" type="submit" value="Submit"></td>
        </tr>
        {% csrf_token %}

        </form>

            <tr>
	        <td>Electronics's Name</td>
	        <td>Number</td>
	        <td>Power (watts)</td>
	        <td>Time (hours/day)</td>
	        <td>Electricity Usage Unit (units)</td>
            </tr>
        {% for electronic in electronics%}
	    <tr>
	        <td>{{ electronic.name }}</td>
	        <td>{{ electronic.number }}</td>
	        <td>{{ electronic.power }}</td>
	        <td>{{ electronic.time }}</td>
	        <td>{{ electronic.unit }}</td>
            </tr>
        {% endfor %}
	    <tr>
	        <td></td>
	        <td></td>
	        <td></td>
	        <td>Sum units</td>
	        <td>{{ sum_unit }} Units</td>
            </tr>
	    <tr>
	        <td></td>
	        <td></td>
	        <td></td>
	        <td>Cost</td>
	        <td>{{ cost_unit }} THB</td>
            </tr>
	    <tr>
	        <td></td>
	        <td></td>
	        <td></td>
	        <td>ft of JAN-APR 2015</td>
	        <td>{{ ft }} Stangs/Unit</td>
            </tr>
	    <tr>
	        <td></td>
	        <td></td>
	        <td></td>
	        <td>Cost (add ft)</td>
	        <td>{{ cost_add_ft }} THB</td>
            </tr>
	    <tr>
	        <td></td>
	        <td></td>
	        <td></td>
	        <td>VAT 7%</td>
	        <td>{{ vat }} THB</td>
            </tr>
	    <tr>
	        <td></td>
	        <td></td>
	        <td></td>
	        <td>NET COST</td>
	        <td>{{ net_cost }} THB</td>
            </tr>
        </table>
    </body>
</html>